### ISSUE TITLE
Hide ‘Heat’ in Homekit?

### ISSUE THREAD

**Issue by Hazza42** [ddenisyuk/homebridge-gree-heatercooler#10]
I’m currently using this to control my EcoAir Gelo AC unit, which doesn’t have a heater function, and I’d like to be able to hide that option within homekit (as the 3 states are currently ‘Heat/Cool/Off’).
Is there an option in the config for that?

**Comment by ddenisyuk** [comment]
Hi, this is impossible to hide predefined required Homekit characteristic 
https://developers.homebridge.io/#/service/HeaterCooler
