### ISSUE TITLE
Last update broke the plugin

### ISSUE THREAD

**Issue by duculete** [ddenisyuk/homebridge-gree-heatercooler#12]
ReferenceError: address is not defined
    at /usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:127:71
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

 console.log("[GreeAC]: _sendBindRequest socket error %s", address, error);

change it to  console.log("[GreeAC]: _sendBindRequest socket error %s", device.address, error);

**Comment by ddenisyuk** [comment]
will fix ASAP

**Comment by ddenisyuk** [comment]
1.0.7

**Comment by duculete** [comment]
you can also include fix for serial number:

.setCharacteristic(Characteristic.SerialNumber, this.host.replace(/ \ ./g, "")); < remove spaces between \ and .

**Comment by ddenisyuk** [comment]
1.0.8

**Comment by vahov** [comment]
The logs are now full with `[GreeAC]: _sendRequest socket error null` errors on 1.0.8. The AC works though.

**Comment by ddenisyuk** [comment]
> The logs are now full with `[GreeAC]: _sendRequest socket error null` errors on 1.0.8. The AC works though.

1.0.9

**Comment by vahov** [comment]
Thank You!!

**Comment by ddenisyuk** [comment]
You are welcome!
