### ISSUE TITLE
acTemp showing -40.0 degree

### ISSUE THREAD

**Issue by ksstsui** [ddenisyuk/homebridge-gree-heatercooler#3]
i have two same model Gree AC and added to Homebridge with below config.json

},
        {
            "accessory": "GreeHeaterCooler",
            "host": "192.168.1.208",
            "name": "Living Room AC",
            "acModel": "C&H",
            "acTempSensorShift": 40,
            "updateInterval": 10000
        },
        {
            "accessory": "GreeHeaterCooler",
            "host": "192.168.1.81",
            "name": "Master Bedroom AC",
            "acModel": "C&H",
            "acTempSensorShift": 40,
            "updateInterval": 10000
        }
    ],

it work fine however, one of the ac keep showing -40.0 degree , any idea how to fix this?

many thanks ! it's 
![IMG_2585](https://user-images.githubusercontent.com/32116312/82062877-57135b00-96fd-11ea-8bf2-9bf1247fa34d.jpg)
make my ac difference.

**Comment by quartist** [comment]
the same for me :/

**Comment by zsiraph** [comment]
same thing for me. Any solution or idea how can I fix that?

**Comment by ghost** [comment]
The `acTempSensorShift` represents the offset between actual temperature and the temperature value returned by AC. In my case, my AC returns the actual temperature so the `acTempSensorShift` should be set to `0`.

**Comment by zsiraph** [comment]
> The `acTempSensorShift` represents the offset between actual temperature and the temperature value returned by AC. In my case, my AC returns the actual temperature so the `acTempSensorShift` should be set to `0`.

I tried that, but it is still -40 for me even if I set acTempSensorShift to 0

**Comment by zsiraph** [comment]
> The `acTempSensorShift` represents the offset between actual temperature and the temperature value returned by AC. In my case, my AC returns the actual temperature so the `acTempSensorShift` should be set to `0`.

I mean if I set acTempSensorShift to -23, homekit will show 23 degrees. So it looks like that there is no temperature value returned by my AC for some reason.

**Comment by Artoria2e5** [comment]
The -40 is likely a way to say `null`. The value is obtained by [subtracting 40 from the raw value](https://github.com/tomikaa87/gree-remote/issues/7#issuecomment-643226342), which would be 0 in this case.

**Comment by ddenisyuk** [comment]
> i have two same model Gree AC and added to Homebridge with below config.json
> 
> },
> {
> "accessory": "GreeHeaterCooler",
> "host": "192.168.1.208",
> "name": "Living Room AC",
> "acModel": "C&H",
> "acTempSensorShift": 40,
> "updateInterval": 10000
> },
> {
> "accessory": "GreeHeaterCooler",
> "host": "192.168.1.81",
> "name": "Master Bedroom AC",
> "acModel": "C&H",
> "acTempSensorShift": 40,
> "updateInterval": 10000
> }
> ],
> 
> it work fine however, one of the ac keep showing -40.0 degree , any idea how to fix this?
> 
> many thanks ! it's
> ![IMG_2585](https://user-images.githubusercontent.com/32116312/82062877-57135b00-96fd-11ea-8bf2-9bf1247fa34d.jpg)
> make my ac difference.

If you have two exact same AC model and only one of them works - this is not an issue of plugin. You can try to update AC firmware and/or reset it to factory settings. This could help, other wise (if models are same) it can be an issues with AC temperature sensor.

**Comment by ddenisyuk** [comment]
@ksstsui try to connect to your AC with https://github.com/tomikaa87/gree-remote and fetch "TemSen" parameter.

**Comment by quartist** [comment]
Hi,

fo me, where I have the same problem (-40C) TemSen parameter have 0.
python3 gree.py -c "IP" -i "ID" -k "KEY" get TemSen
Getting parameter: TemSen
TemSen = 0

**Comment by ddenisyuk** [comment]
It seems your AC doesn't have builded in temperature sensor or it have different key in API. 

You can try to fetch all known API keys (https://github.com/tomikaa87/gree-remote/issues/7#issuecomment-410212648) and try to determinate is there any other parameter with the temperature. 

Or just update "acTempSensorShift" config with "0" value to avoid "-40"

**Comment by ddenisyuk** [comment]
Hi
New configuration property in available in v1.0.5 - "useTargetTempAsCurrent". 
It could be used for AC W/O builded in temp sensor. 
Target temperature will be shown as a current if this property is "true".

FYI @ksstsui and @quartist

This is the maximum what I can do from plugin side. If you know how we can solve this issue in other way fill free to open new issue and/or PR.
