### ISSUE TITLE
After update to 1.0.5 [ERR_SOCKET_BAD_PORT]

### ISSUE THREAD

**Issue by ronnieSVK** [ddenisyuk/homebridge-gree-heatercooler#7]
Dear Developer !

Compliments for your fantastic work and thank you for the oportunity to use our devices with this great plugin !
This is my first post here, i hope is on "good place" :)

Im daily user of your plugin in HOOBS with COOLEXPERT AC (running on 24/7 MacMini) maybe since 1 year ago. Sadly i dont know which version was recent that times. Everything worked absolutely fantastic ! Easy config, easy use. The actual room temperature was also shown in HomeKit (sensor in AC, the temperature data was +- also accurate). The HOOBS offered me an update to the recent 1.0.5 version. Since this time the temperature value in HOOBS shows -40c, the AC is found by Homebridge/HOOBS, shown in HomeKit as "online" but its not responding to commands. If i press some button in Home the terminal logs shows following errors :  

![IMG_0939](https://user-images.githubusercontent.com/67477813/86282083-d7731a00-bbde-11ea-9956-9757c852b1dd.jpeg)

Plugin was updated, then deleted, reinstalled in HOOBS, but the result is always absolutely the same (checked everytime logs also). EWPE smart works without any problem.

Can you please help to resolve this issue ?

Thank you very much ! Keep the fantastic work going !

**Comment by ddenisyuk** [comment]
Hi @ronnieSVK, 
try to reboot your AC (disable and then enable power supply) and then reboot your HOOBS device

**Comment by 3zero2** [comment]
I am getting the same error. I tried to power cycle the AC and then the Homebridge device, but that didn't work. This is the first time I'm using homebridge-gree-heatercooler, so I don't know if a previous version would have worked.

My current config is: 
```
"accessory": "GreeHeaterCooler",
            "host": "192.168.1.127",
            "name": "Living Room AC",
            "acModel": "C&H",
            "useTargetTempAsCurrent": true,
            "updateInterval": 10000
```

My AC model is: GWH24YE-K6DNA1A/I(WIFI)

Is my config correct?

**Comment by 3zero2** [comment]
I had the same problem and the issue for me was an incorrect IP address specified in the config.

**Comment by mrcemento** [comment]
exactly same issue here, compatibility broken by app update. [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received 0

**Comment by glenncalleja** [comment]
Same here.. I'm not familiar with node.js but I tried experimenting a bit with the code, seems like sometimes (actually most of the times) the AC is not responding and 'this.socket.on('message' ...' is never being called. Intermittently, I restart and it worked.

What's weird is that I don't see any recent update in this particular plugin which could cause this, so I'm unsure if this is something related to this plugin or some update to some other component.

I have the latest Homebridge, 2 Gree Acs, and Google-wifi. This used to work well until very recently. If I find any further clues as to what's happening I can comment.

Edit: Downgrading to v1.0.2 makes it worse since the plugin crashes there, so seems like something has changed..

**Comment by iMike96** [comment]
I saw this error once in the homebridge log, and it works rarely and very randomly. Siri said that she set the temperature to the desired level, but nothing happened. When it works there is a 10-20 second delay between the Siri request and the command. The funniest thing is that I can't log in to my account through Gree+ app as well, tried to create a new account and re-add the AC to it but didn't work. Also tried rebooting serveral times both the HomeBridge and AC but none of them worked.

**Comment by glenncalleja** [comment]
Yeah, I investigated this further and this seems to be an issue with Gree servers in Europe at least currently. 
What seems to have worked is creating a new account in the Gree app but in the North America region. I then added the ACs to the Gree app, and restarted Homebridge. It seems to be working consistently now.

**Comment by 3zero2** [comment]
@glenncalleja Keep us updated please if it keeps on working. I was thinking that we might be reaching some API limits;

**Comment by iMike96** [comment]
I am also using the European servers, but I'll try this trick as well and see if it works.

**Comment by iMike96** [comment]
Well, it actually works better than the EU server did. Faster than ever! Thanks @glenncalleja !

**Comment by glenncalleja** [comment]
@3zero2 Yes, it's still working. There definitely was/is(?) something wrong with the European servers, and it seems that the ACs stop responding to local requests if they can't connect to the Gree servers.

**Comment by iMike96** [comment]
It is working for me as well without problems.
