### ISSUE TITLE
AC displaying current temperature -40

### ISSUE THREAD

**Issue by teymur1988** [ddenisyuk/homebridge-gree-heatercooler#8]
Hi there,

I've just purchased Gree AC GWH12YC-K3DNA2G, that is an invertor model with WiFi, it's current year's model. After adding it to homekit it shows current temperature as "-40" and stays there. Is there anything I can do about it other than setting "useTargetTempAsCurrent": true, ???

Regards

Teymur

**Comment by ddenisyuk** [comment]
Hi @teymur1988,
try to reboot your AC (disable and then enable power supply) and then reboot your homebridge device

**Comment by teymur1988** [comment]
> Hi @teymur1988,
> try to reboot your AC (disable and then enable power supply) and then reboot your homebridge device

I did do that, I deleted the AC from GREE+ app, powercycled the AC, added again. Same thing. I even installed the plugin on a different computer alltogether - still the same. What am I missing? If you could kindly help me with this I will provide all information I can, even the remote access if that's needed.

**Comment by ddenisyuk** [comment]
Seams you have same issue https://github.com/ddenisyuk/homebridge-gree-heatercooler/issues/3.

Unfortunately  I can't help you. https://github.com/ddenisyuk/homebridge-gree-heatercooler/issues/3#issuecomment-649775427

**Comment by galzil** [comment]
@teymur1988 What firmware version do you have?
As mentioned [here](https://github.com/norberttech/homebridge-ch-ac/issues/3), this problem popped up with version 3.7

**Comment by galzil** [comment]
New firmware 3.72 solves this issue!

**Comment by teymur1988** [comment]
> New firmware 3.72 solves this issue!

Thanks! I just updated my 2 GreeACs to 3.72 looks like the problem is solved.
